


import React, { useEffect, useRef, useState } from 'react';
import Icon from './Icon';
import LoadingSpinner from './LoadingSpinner';
import MarkdownRenderer from './MarkdownRenderer';

interface PRDModalProps {
  isOpen: boolean;
  onClose: () => void;
  content: string;
  isLoading: boolean;
  onSave?: (title: string, content: string, type: 'prd') => void;
}

const PRDModal: React.FC<PRDModalProps> = ({ isOpen, onClose, content, isLoading, onSave }) => {
  const modalRef = useRef<HTMLDivElement>(null);
  const [isExportMenuOpen, setIsExportMenuOpen] = useState(false);
  const exportMenuRef = useRef<HTMLDivElement>(null);
  const [isSaved, setIsSaved] = useState(false);

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (exportMenuRef.current && !exportMenuRef.current.contains(event.target as Node)) {
        setIsExportMenuOpen(false);
      }
    };
    if (isExportMenuOpen) document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [isExportMenuOpen]);

  const handleBackdropClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if (modalRef.current === event.target) onClose();
  };

  const handleSave = () => {
      if (onSave) {
          onSave('Product Requirements Document', content, 'prd');
          setIsSaved(true);
          setTimeout(() => setIsSaved(false), 2000);
      }
  };

  // Export Functions
  const downloadFile = (data: string, filename: string, mimeType: string) => {
      const blob = new Blob([data], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setIsExportMenuOpen(false);
  };

  const handleExportMD = () => downloadFile(content, 'prd-spec.md', 'text/markdown');
  const handleExportTXT = () => downloadFile(content, 'prd-spec.txt', 'text/plain');

  const handleExportPDF = () => {
      const printWindow = window.open('', '_blank');
      if (!printWindow) return;

      // Convert Markdown-ish structure to HTML for printing
      let formattedHtml = content
        .replace(/^# (.*$)/gim, '<h1>$1</h1>')
        .replace(/^## (.*$)/gim, '<h2>$1</h2>')
        .replace(/^### (.*$)/gim, '<h3>$1</h3>')
        .replace(/\*\*(.*)\*\*/gim, '<b>$1</b>')
        .replace(/`([^`]*)`/gim, '<code>$1</code>')
        .replace(/```([\s\S]*?)```/gim, '<pre>$1</pre>')
        .replace(/\n/gim, '<br />');

      const printDoc = `
          <html>
          <head>
              <title>Product Requirements Document</title>
              <style>
                  body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; }
                  h1 { font-size: 2.5em; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-bottom: 20px; color: #111; }
                  h2 { font-size: 1.8em; margin-top: 30px; border-bottom: 1px solid #eee; color: #222; }
                  h3 { font-size: 1.4em; margin-top: 20px; color: #444; }
                  p { margin-bottom: 1em; }
                  code { background: #f4f4f4; padding: 2px 5px; border-radius: 3px; font-family: monospace; border: 1px solid #ddd; color: #d63384; }
                  pre { background: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto; border: 1px solid #e9ecef; font-family: monospace; white-space: pre-wrap; }
                  .meta { margin-bottom: 40px; color: #666; font-size: 0.9em; border-left: 4px solid #0d9488; padding-left: 10px; }
              </style>
          </head>
          <body>
              <div class="meta">Generated by GitOn • PRD Spec • ${new Date().toLocaleDateString()}</div>
              ${formattedHtml}
          </body>
          </html>
      `;

      printWindow.document.write(printDoc);
      printWindow.document.close();
      setTimeout(() => {
          printWindow.focus();
          printWindow.print();
          printWindow.close();
      }, 250);
      setIsExportMenuOpen(false);
  };

  if (!isOpen) return null;

  return (
    <div
      ref={modalRef}
      className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-[60] p-4 animate-fade-in"
      onClick={handleBackdropClick}
    >
      <div className="bg-gray-900 border border-white/20 rounded-2xl shadow-2xl w-full max-w-4xl h-[90vh] flex flex-col overflow-hidden relative">
        
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-white/10 bg-gray-800/50 z-10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-teal-500/20 rounded-lg flex items-center justify-center border border-teal-500/30">
                <Icon icon="document" className="w-6 h-6 text-teal-300" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">Product Requirements Document</h2>
              <p className="text-sm text-gray-400">Vibe-Spec Framework for AI Coding</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
              {/* Save Button */}
              {onSave && !isLoading && (
                  <button
                      onClick={handleSave}
                      className="flex items-center gap-2 px-3 py-2 bg-blue-600/20 hover:bg-blue-600/40 border border-blue-500/30 rounded-lg text-sm text-blue-300 transition-colors"
                      title="Save to Project Library"
                  >
                      {isSaved ? <Icon icon="check" className="w-4 h-4 text-green-400" /> : <Icon icon="save" className="w-4 h-4" />}
                      <span className="hidden sm:inline">{isSaved ? 'Saved' : 'Save'}</span>
                  </button>
              )}

              <div className="relative" ref={exportMenuRef}>
                  <button
                      onClick={() => setIsExportMenuOpen(!isExportMenuOpen)}
                      className="flex items-center gap-2 px-3 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-sm text-gray-300 transition-colors"
                      disabled={isLoading}
                  >
                      <Icon icon="download" className="w-4 h-4" />
                      <span>Export</span>
                  </button>
                  
                  {isExportMenuOpen && (
                      <div className="absolute right-0 mt-2 w-48 bg-gray-800 border border-white/10 rounded-lg shadow-xl z-50 animate-fade-in-sm overflow-hidden">
                          <button onClick={handleExportMD} className="w-full text-left px-4 py-3 text-sm text-gray-300 hover:bg-white/10 hover:text-white transition-colors flex items-center gap-2">
                              <span className="uppercase text-xs font-bold text-purple-400 w-8">MD</span>
                              Markdown
                          </button>
                           <button onClick={handleExportTXT} className="w-full text-left px-4 py-3 text-sm text-gray-300 hover:bg-white/10 hover:text-white transition-colors flex items-center gap-2 border-t border-white/5">
                              <span className="uppercase text-xs font-bold text-blue-400 w-8">TXT</span>
                              Text File
                          </button>
                          <button onClick={handleExportPDF} className="w-full text-left px-4 py-3 text-sm text-gray-300 hover:bg-white/10 hover:text-white transition-colors flex items-center gap-2 border-t border-white/5">
                              <span className="uppercase text-xs font-bold text-pink-400 w-8">PDF</span>
                              Print / PDF
                          </button>
                      </div>
                  )}
              </div>

              <button onClick={onClose} className="text-gray-400 hover:text-white p-2 rounded-full hover:bg-white/10 transition-colors">
                <Icon icon="close" className="w-6 h-6" />
              </button>
          </div>
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-8 custom-scrollbar">
            {isLoading ? (
                <div className="flex flex-col items-center justify-center h-full space-y-4">
                    <LoadingSpinner />
                    <p className="text-gray-400 animate-pulse">Drafting comprehensive specifications...</p>
                </div>
            ) : (
                <div className="prose-custom max-w-none">
                    <MarkdownRenderer content={content} />
                </div>
            )}
        </div>
      </div>
      <style>{`
            .custom-scrollbar::-webkit-scrollbar { width: 6px; }
            .custom-scrollbar::-webkit-scrollbar-track { background: rgba(0,0,0,0.1); }
            .custom-scrollbar::-webkit-scrollbar-thumb { background-color: rgba(255, 255, 255, 0.2); border-radius: 10px; }
            .custom-scrollbar::-webkit-scrollbar-thumb:hover { background-color: rgba(255, 255, 255, 0.3); }
            @keyframes fade-in-sm {
                from { opacity: 0; transform: scale(0.95); }
                to { opacity: 1; transform: scale(1); }
            }
            .animate-fade-in-sm {
                animation: fade-in-sm 0.1s ease-out forwards;
                transform-origin: top right;
            }
      `}</style>
    </div>
  );
};

export default PRDModal;